//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewRedemption
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InterviewRedemptionEntities2 : DbContext
    {
        public InterviewRedemptionEntities2()
            : base("name=InterviewRedemptionEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Property> Propertys { get; set; }
        public virtual DbSet<TicketRecord> TicketRecords { get; set; }
        public virtual DbSet<Container> Containers { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
    }
}
